import { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
    title: 'Home',
    description: 'Generated by create next app',
};
export default function Home() {
    return (
        <main>
            <h1 className="text-center text-4xl font-bold">Home</h1>
        </main>
    );
}
